behaviors:
    Car:
        trainer_type: sac
        hyperparameters:
            buffer_init_steps: 1000
            init_entcoef: 2.0
            batch_size: 128
            buffer_size: 50000
        network_settings:
            normalize: true
            hidden_units: 512
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.9999
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 1000000
        time_horizon: 128
        summary_freq: 5000
        threaded: true
